openbikesensor/openbikesensor.github.io

- index.md
> Video link update

- benutzer-anleitung/index.md
- benutzer-anleitung/konfiguration.md
- benutzer-anleitung/messfahrt.md
- benutzer-anleitung/montage.md
Based and on a posted German translation in the OBS Slack workspace and the English instruction an initial German user guide has been added.
> German Documentation

- _includes/build-instructions.md
> Format markdown in long build instructions, remove latex references

- content/en/docs/hardware/v00.03/build-instructions/index.de.md
Please have a look at the URLs (to Slack, Configuration and User-Guide). Locally, they work for me.
> Updated instructions after building an OpenBikeSensor myself

- config.toml
> Fix linked branch from "master" to "main".

- content/en/docs/hardware/models.md
- content/en/docs/hardware/v00.02/build-instructions/index.de.md
- content/en/docs/hardware/v00.03/build-instructions/index.de.md
@opatut because you asked to get #23 done.. 
.. and some other improvements
> Improved manuals

- content/en/docs/hardware/parts/_index.en.md
Please check carefully that I have not screwed anything up too much by reformatting it :)
> Reformat and extend parts page

- content/_index.de.html
Originally created over at @madiko's fork, I reopen this inside this repository so we can all collaborate on the changes. See also #58.
> Homepage content changes

- content/docs/user-guide/quickstart.de.md
Just some small adjustments, and links to futher docs.
> Update quickstart guide

- content/docs/hardware/parts/_index.en.md
- some information has been refined
- the parts from the saved shopping list are added as single positions into the parts list
> Parts list updated.

- content/blog/2021-03-23-obs-goes-lgpl/index.de.md
- content/blog/_index.de.md
**Note:** Wait for [discussion in Slack](https://openbikesensor.slack.com/archives/C014LFDU8SX/p1618219256005900) to approve of the Blog section before merging this. **Edit:** It appears everybody is fine with that.
> Start a blog, with a post about our recent LGPL licensing

- content/blog/2021-03-23-obs-goes-lgpl/index.de.md
- content/blog/2021-03-28-fernsehbeitrag-ard-swr/index.de.md
Maybe solves #61, at least we have put it *somewhere* then.
@openbikesensor/website-team Please consider improving my very badly written accompanying blog text.
For those who don't want to build it themselves: Here is what it looks like with the embedded video:
> Blog Post zu Fernsehbeitrag ARD/SWR

- content/docs/hardware/parts/_index.en.md
The new case uses fewer screws and uses heat-set inserts instead.
> Amend parts list for changes in the case design.

- content/docs/hardware/v00.03.12/build-instructions/_index.de.md
- content/docs/hardware/v00.03.12/parts/_index.de.md
added for
- JST-XH Crimp-Kontakte
- Batteriekabel und Platinenstecker
- Gewindeeinsatz / Einpressmutter
> Add links to parts ordered for the February collective order.

- content/blog/2021-06-17-zu-gast-im-achter/index.de.md
Hallo zusammen, 
mein erster Blogbeitrag. Ich hoffe sehr, es klappt technisch und der Beitrag trifft auf Eure Zustimmung.
Viele Grüße,
Franziska
> Blogbeitrag "OpenBikeSensor zu Gast im Achter"

- README.md
@opatut i'd suggest to also adapt the readme to reflect the new workflow.
> Add remark about how to contribute

- content/docs/hardware/v00.03.12/build-instructions/_index.de.md
- content/docs/user-guide/configuration/minimal/index.de.md
@opatut This is the combined content of #98 and #99 - with your requested changes addressed.
I had to make a new PR because I had removed and re-created my fork while experimenting with the staging website build settings on my gh-pages account which lost me the source branch of the two PRs. Tried fixing it by recreating a branch of the same name but to no avail. Apologies for the arising inconvenience.
Regarding the part about "Leiterschleife": my assumption is that we have some high frequency current variation on those wires due to the 3.3V buck converter despite running on direct current and buck converters are. But you correctly mentioned twisted wires look nicer anyhow so for lack of an oscilloscope I removed the remark about wire loops because it was speculative.
> Experiences from Darmstadt builds

- assets/scss/_styles_project.scss
- content/docs/hardware/general/case/_index.de.md
@nosch2021 created a nice 3d printing guide, and I took the time to format it a little and adjust writing and formatting style to the rest of the docs. Thanks @nosch2021 for the original work!
> Format and finetuning for new 3D printing page

- content/docs/firmware/flash-linux.de.md
Text is theft from Windows configuration description
> added lnk to Basis configuration

- assets/scss/_styles_project.scss
- config.toml
- content/_index.de.html
- content/community/_index.de.md
- content/community/_index.en.md
- content/verein.de.md
- layouts/shortcodes/blocks/cover.html
- layouts/shortcodes/imgproc.html
Mobile view had a few minor issues
* Dropdown not working in scrollable navigation 
* Text on cover image overflowing the page
* Image "Visualisierung" squeezed in wrong aspect ratio
* `<pre>` content overflowing page
> Homepage overflow fix

- content/docs/software/_index.de.md
- content/docs/software/visualization/_index.de.md
Thanks to community user `Pepo`, we have another bit of documentation, this time concerning offline visualization, i. e. "the old way" of getting the data visualized (manually, without a portal). This is still relevant for a while, so why not publish it on the website?
Thanks, Pepo!
> Tutorial for offline visualization

- content/docs/hardware/v00.03.12/build-instructions/_index.de.md
- static/html/BOM_00.03.12.html
This PR adds an interactive BOM from the PCB repository and links it in the build instructions.
> Interactive BOM

- content/docs/hardware/v00.03.12/build-instructions/_index.de.md
> Add alternative to bending the sensor board contact pins.

- config.toml
- content/map.de.md
as discussed in community meeting: add the map - navigation location might change in the future.
> Merge the map

- content/map.de.md
@dboldt breaks the map height a little but I found no way to determine height of the content div.
> add descriptive text

- content/docs/user-guide/configuration/advanced.de.md
- content/docs/user-guide/configuration/advanced.en.md
- content/docs/user-guide/configuration/minimal/index.de.md
- content/docs/user-guide/quickstart.de.md
> Remove references to HLRS portal and link to forum post instead 

- content/contact/_index.de.md
- content/verein.de.md
Der Verein ist eingetragen, Impressum und Vereinsseite entsprechend angepasst
> Verein Eintragung

- content/docs/hardware/troubleshooting/_index.de.md
- layouts/docs/list.html
Started a troubleshooting page with some links to forum posts where people describe solutions to common problems. Just to get this started, please extend if you find more.
Solves #145.
> Troubleshooting page

- content/docs/hardware/v00.03.12/parts/_index.de.md
Deadlink gelöscht, hinweis auf derzeitige Testbestellung hinzugefügt.
> a bit more maintenance on the parts page

- content/docs/hardware/v00.03.12/parts/_index.de.md
- Supermagnete (me)
- reichelt for switch from https://forum.openbikesensor.org/t/erfahrungen-mit-bauteilen-von-anderen-haendlern-lieferanten/1301/7 by ccoors
- androegg for sd reader from https://forum.openbikesensor.org/t/erfahrungen-mit-bauteilen-von-anderen-haendlern-lieferanten/1301 by ccoors
> Add some links to suppliers

- content/docs/hardware/v00.03.12/parts/_index.de.md
> Add link to shop androegg.de for JSN-SR04T-v3.0.

- content/docs/firmware/_index.de.md
> Notizen zum Bau der Firmware aus dem github Repo

- content/docs/hardware/v00.03.12/build-instructions/_index.de.md
* Fix minor typos
* `&thinsp;` before units such as `mm` or `cm`
* Some `.`s at the end of sentences/ bullet points.
> Fix typos, try to make formatting more consistent

- content/_index.en.html
- content/docs/hardware/general/_index.en.md
- content/docs/user-guide/quickstart.en.md
- content/map.en.md
I added the map for the English side, made some language corrections in the quick start page, and changed a link because "start" is better than "about" when referencing your main landing page.
> En pages 1

- content/docs/hardware/troubleshooting/_index.de.md
- content/docs/user-guide/quickstart.de.md
Add some troubleshooting information that I orally relay during workshops and that I think make sense to have as part of the documentation.
> Add troubleshooting information
